### ISSUE TITLE
Spellcheck in TEX Documents?

### ISSUE THREAD

**Issue by BrandenEsses** [ijmbarr/jupyterlab_spellchecker#30]
I'm trying to have the extension work on .tex documents. It works on LaTEX class files (.cls) out of the box.  I tried adding 'text/x-tex' to the [accepted type list ](https://github.com/ijmbarr/jupyterlab_spellchecker/blob/89e23c1a9a6df484c878ec39a098bfdf0eaeafb1/src/index.ts#L101-L104) in index.ts, but to no avail. It seems that [.tex documents are a subset of 'text/plain'](https://reposcope.com/mimetype/text/x-tex), and I am not sure where to go from here.

Apologies if this is not the correct place for this - I am new to GitHub.

**Comment by krassowski** [comment]
It seems that lab uses `text/latex` mimetype for tex documents as per [file formats documentation](https://github.com/jupyterlab/jupyterlab/blob/3d0067aaf085b328c958c9cd74b7aa87e71252bf/docs/source/user/file_formats.rst#latex). Would that work for you?

**Comment by BrandenEsses** [comment]
Thanks for your quick reply!

I went ahead and changed it to:
```
accepted_types = [ 
        'text/plain',
        'text/x-ipythongfm',   // IPython GFM = GitHub Flavored Markdown, applies to all .md files
        'text/latex',
    ]; 
```
I rebuilt  with:
```
npm run build
jupyter lab build
```
But no dice. So I completely uninstalled, rebuilt and reinstalled, but still no luck. Am I missing anything?

**Comment by krassowski** [comment]
I would try one more command (if you have not already): `jupyter labextension link .`

If you are not sure if your changes are being picked up, you could always try to add an `alert()` call somewhere in the code.

Feel free to post the result of `jupyter labextension list`. Also, you may be interested in the tex support we have over in jupyterlab-lsp extension.

**Comment by BrandenEsses** [comment]
I've decided to focus my attention on jupyterlab-lsp. Thank you for the support!

**Comment by QZ4869** [comment]
You need use `text/x-latex` instead of `text/latex` 

```javascript
accepted_types = [ 
        'text/plain',
        'text/x-ipythongfm',   // IPython GFM = GitHub Flavored Markdown, applies to all .md files
        'text/x-latex',
    ]; 
```

**Comment by krassowski** [comment]
Thanks @QZ4869! It should be now possible to change the types for the user interface (see #32).
