### ISSUE TITLE
Where can we see the spellchecker suggestions?

### ISSUE THREAD

**Issue by paugier** [ijmbarr/jupyterlab_spellchecker#34]
> Spellchecker suggestions are available from the context menu.

I guess I'm just silly but I can't find how to get the suggestions!

I tried to right-click on a wrong word but there is nothing on spelling suggestions in the context menu.

**Comment by krassowski** [comment]
What version of the JupyterLab and of the extension do you use? You can check this with:

```bash
jupyter lab --version
``

and

```bash
jupyter labextension list
``

respectively

**Comment by paugier** [comment]
```
$ jupyter lab --version                                                  
2.1.1
$ jupyter labextension list                                              
JupyterLab v2.1.1
Known labextensions:
   app dir: /home/pierre/.pyenv/versions/3.8.2/share/jupyter/lab
        @ijmbarr/jupyterlab_spellchecker v0.1.6  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyter-leaflet v0.13.2  enabled  OK
        jupyter-matplotlib v0.7.4  enabled  OK
```

**Comment by krassowski** [comment]
You will need JupyterLab 2.2.2 to install the newest version of the extension right now (and >=2.2.2 once #35 gets merged and a new version is released). Upgrade your JupyterLab to 2.2.2 with:

```bash
pip install jupyterlab=2.2.2
# or conda equivalent - whichever you used to install it in the first place
```

Then upgrade the extension with:

```bash
jupyter labextension install @ijmbarr/jupyterlab_spellchecker@0.1.9`
```

**Comment by paugier** [comment]
Ah great!! I confirm that it is now fixed!

Sorry for this bad issue and thanks for this very useful extension!

**Comment by krassowski** [comment]
No, you did help a lot - your message lead me to diagnosing and fixing a
bug in the code which prevented the new extension version from getting
installed in newer JupyterLab versions! Thank you and have a great weekend!
