### ISSUE TITLE
How to see suggestions?

### ISSUE THREAD

**Issue by stefaneidelloth** [ijmbarr/jupyterlab_spellchecker#37]
>Spellchecker suggestions are available from the context menu.

The context menu does not seem to provide any suggestions:

![image](https://user-images.githubusercontent.com/12675339/97206081-9075e980-17b8-11eb-8cb9-e696deeae0c7.png)

**Comment by krassowski** [comment]
See #34

**Comment by krassowski** [comment]
1. Update the extension to the newest version (0.1.10) with:

```bash
jupyter labextension update @ijmbarr/jupyterlab_spellchecker
```

2. Refresh window with JupyterLab (or restart it), 

3. Use the context menu over a word you want to correct, see gif below:

![spellcheck](https://user-images.githubusercontent.com/5832902/88500326-41a19380-cfc0-11ea-9851-1c8edf7845f1.gif)

**Comment by stefaneidelloth** [comment]
Thanks a lot!
