### ISSUE TITLE
How to add custom words to the dictionary?

### ISSUE THREAD

**Issue by stefaneidelloth** [ijmbarr/jupyterlab_spellchecker#38]
If there is a word that is spelled correctly I would like to have a context menu option to add
it to (a wanted) dictionary.

**Comment by krassowski** [comment]
1. Update the extension to the newest version (0.1.10) with:

```bash
jupyter labextension update @ijmbarr/jupyterlab_spellchecker
```

2. Refresh window with JupyterLab (or restart it), 

3. Use the context menu over a word you want to save (via `Ignore` option), or go Advanced Settings Editor, see gif below:

![ignore](https://user-images.githubusercontent.com/5832902/89849819-3eda9d00-db81-11ea-8433-dc38e07b075b.gif)

**Comment by stefaneidelloth** [comment]
Thanks a lot!
