### ISSUE TITLE
Any way to use other dictionaries?

### ISSUE THREAD

**Issue by jretamales** [ijmbarr/jupyterlab_spellchecker#4]
Thanks for this project. Although, in the README it's mentioned that only English is supported. It still begs the question if changing the urls in [index.ts](https://github.com/ijmbarr/jupyterlab_spellchecker/blob/master/src/index.ts) for a different dictionary will work. Would it?

**Comment by ijmbarr** [comment]
You're right - changing the url will load a different dictionary.

**Comment by jretamales** [comment]
Thanks!
