### ISSUE TITLE
Update for jupyterlab-0.33.11 ?

### ISSUE THREAD

**Issue by sean-parent** [ijmbarr/jupyterlab_spellchecker#6]
Current extension doesn't work with latest jupyterlab.

**Comment by aapeebles** [comment]
I second this comment. Any timeline for an update?

**Comment by ijmbarr** [comment]
I took a quick look at this: it looks like thing are more complicated than just updating the dependencies. Something in the new release is breaking some of the functionality of this extension. 

It is likely to be a few weeks before I get a chance to dig into what the issue is.

**Comment by ijmbarr** [comment]
The issues should be fixed now, up to version 0.34.
