### ISSUE TITLE
Spell checker highlighting and dark theme

### ISSUE THREAD

**Issue by wyuill** [ijmbarr/jupyterlab_spellchecker#9]
Spell checking on jupyterlab dark theme is very hard to see. Could the highlighting colour be changed to a colour that works for both white and black backgrounds (or better yet a user choice).

Thanks

**Comment by ijmbarr** [comment]
Hi Wyuill - you should be able to change the style by altering the value in style/index.css.

**Comment by wyuill** [comment]
Thanks for the help
